kind: pipeline
type: docker
name: default

steps:
- name: fixperms
  image: imrehg/archlinux-makepkg
  user: root
  commands:
  - chown -R builder:builder .
- name: build
  image: imrehg/archlinux-makepkg
  commands:
  - yay -Suy --noconfirm
  - namcap PKGBUILD
  - makepkg -sci --noconfirm
  - namcap *.pkg.tar.zst

